name: 'Send Email Notification'
description: 'Send email for the github build'
inputs:
  from_email:
    description: 'Sender of the email'
    required: true
  to_email:
    description: 'Receiver of the email'
    required: true
  subject:
    description: 'Subject of the email'
    required: true
  authorised_username:
    description: 'Authorised username for SMTP authentication'
    required: true
  authorised_password:
    description: 'Authorised password for SMTP authentication'
    required: true
  job_status:
    description: 'The success status of the job in the pipeline'
    required: true
  server_address:
    description: 'The SMTP address to connect to'
    required: true
  server_port:
    description: 'The SMTP port to connect to'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.from_email }}
    - ${{ inputs.to_email }}
    - ${{ inputs.subject }}
    - ${{ inputs.authorised_username }}
    - ${{ inputs.authorised_password }}
    - ${{ inputs.job_status }}
    - ${{ inputs.server_address }}
    - ${{ inputs.server_port }}